name: Releases
on:
  push:
    branches:
      - master
jobs:
  release:
    if: "!contains(github.event.commits[github.event.commits.length - 1].message, '[skip]')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup Node v10.x
        uses: actions/setup-node@v1
        with:
          node-versio: '10.x'
      - name: Setup Github users
        run: |
          git config --local user.email "seokju.me@gmail.com"
          git config --local user.name "seokju-na"
      - name: Checking for missing change logs
        run: |
          set -e
          git remote set-url origin https://seokju-na:${{secrets.GITHUB_PUBLISH_TOKEN}}@github.com/seokju-na/geeks-log
          git fetch origin master:refs/remotes/origin/master -a
          node common/scripts/install-run-rush.js change -v
      - name: Installing
        run: |
          node common/scripts/install-run-rush.js install
      - name: Building
        run: |
          node common/scripts/install-run-rush.js rebuild --verbose
      - name: Version Bump
        run: |
          node common/scripts/install-run-rush.js version \
          --target-branch master \
          --version-policy default \
          --bump
      - name: Publish
        run: |
          node common/scripts/install-run-rush.js publish \
          --apply \
          --publish \
          --target-branch master \
          --include-all \
          --add-commit-details \
          --set-access-level public \
          --npm-auth-token ${{secrets.NPM_TOKEN}}
        env:
          FIREBASE_TOKEN: ${{secrets.FIREBASE_TOKEN}}
